voting-app:
  image: $DTR/admin/voting-app-dev:$GIT_COMMIT
  ports:
    - "5000:80"
redis:
  image: redis
  ports: ["6379"]

worker:
  image: $DTR/admin/worker-dev:$GIT_COMMIT

db:
  image: postgres:9.4

result-app:
  image: $DTR/admin/result-app-dev:$GIT_COMMIT
  ports:
    - "5001:80"
